#!/bin/bash

apt -y remove neovim neovim-runtime vim-common vim-tiny
cd /tmp
wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
apt -y install ./nvim-linux64.deb

[ -f /usr/local/bin/vim ] || ln -s /bin/nvim /usr/local/bin/vi
[ -f /usr/local/bin/vim ] || ln -s /bin/nvim /usr/local/bin/vim
rm -f ./nvim-linux64.deb

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
