#!/bin/bash
cd ~
set -x

# Pip packages are already added in the installer
# sudo python3 -m pip install yapf pynvim neovim

# Optionally, python2 can be installed, although not recommended
# ./install.pip2

# Setup environment
rm -rf .vim .Xresources .style.yapf .config/nvim/bundle
mkdir -p .ctags .local/share/nvim/shada/
touch .local/share/nvim/shada/
ln -s .config/nvim .vim
ln -s .config/nvim/_Xresources .Xresources
ln -s .config/nvim/_style.yapf .style.yapf

# Setting up Vundle and plugins
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
cp -v .config/nvim/init.vim.bare .config/nvim/init.vim
vim -s .config/nvim/vim.setup
vim --headless -s .config/nvim/vim.setup.post
cp -v .config/nvim/init.vim.full .config/nvim/init.vim
docker run -ti --rm -v ~/.config/nvim/bundle/coc.nvim/:/app --workdir /app node yarn install
/usr/bin/sudo /bin/chown -R $(/usr/bin/id -un): ~/.config/nvim
